### ISSUE TITLE
Правапic

### ISSUE THREAD

**Issue by green2005** [Alroniks/pravilnaby#2]
Дробная памылка ў апicаннi.
"З пачатку патрэбна скланіраваць рэпазіторый"
Правiльна будзе так:
"Спачатку ..."

**Comment by Eastindia** [comment]
Тогда уж и скланіраваць -> кланаваць, согласно §23.2

**Comment by Alroniks** [comment]
Дзякуй за падказкі і выпраўленні. Тэхнічны файл паправіў і дапоўніў.
